dramatiq_dashboard/urls.py
from django.urls import path

from dramatiq_dashboard.views import (
    TaskArchiveView,
    TaskDayArchiveView,
    TaskDetailView,
    TaskListView,
    TaskMonthArchiveView,
    TaskYearArchiveView,
)

app_name = "django_dramatiq_dashboard"

urlpatterns = [
    path("executed/", TaskListView.as_view(), name="executed_list"),
    path("executed/<str:id>/", TaskDetailView.as_view(), name="executed_detail"),
    path("archive/", TaskArchiveView.as_view(), name="task_archive"),
    path(
        "archive/<int:year>/", TaskYearArchiveView.as_view(), name="task_year_archive"
    ),
    path(
        "archive/<int:year>/<int:month>/",
        TaskMonthArchiveView.as_view(month_format="%m"),
        name="task_month_archive",
    ),
    path(
        "archive/<int:year>/<int:month>/<int:day>/",
        TaskDayArchiveView.as_view(month_format="%m"),
        name="task_day_archive",
    ),
]

dramatiq_dashboard/models.py
from django.urls import reverse
from django_dramatiq.models import Task


class DramatiqTask(Task):
    def get_absolute_url(self):
        return reverse(
            "django_dramatiq_dashboard:executed_detail", kwargs={"id": self.id}
        )

    class Meta:
        proxy = True

dramatiq_dashboard/views.py
from django.views.generic import ArchiveIndexView, DetailView, ListView, YearArchiveView
from django.views.generic.dates import DayArchiveView, MonthArchiveView

from dramatiq_dashboard.models import DramatiqTask
from dramatiq_dashboard.utils import DateTimeMixin, DynamicDateFieldMixin


class TaskListView(DateTimeMixin, ListView):
    model = DramatiqTask
    template_name = "dramatiq_dashboard/list.html"


class TaskDetailView(DateTimeMixin, DetailView):
    model = DramatiqTask
    template_name = "dramatiq_dashboard/detail.html"
    pk_url_kwarg = "id"

    def get_result(self, obj):
        message = getattr(obj, "message", None)
        try:
            return message.get_result() if message else None
        except Exception:
            return None

    def get_context_data(self, **kwargs):
        context = {}
        obj = self.get_object()
        obj.result = self.get_result(obj)
        context["object"] = obj
        return super(TaskDetailView, self).get_context_data(**context)


class TaskArchiveView(DateTimeMixin, DynamicDateFieldMixin, ArchiveIndexView):
    model = DramatiqTask
    template_name = "archive.html"


class TaskYearArchiveView(DateTimeMixin, DynamicDateFieldMixin, YearArchiveView):
    model = DramatiqTask
    template_name = "archive_year.html"
    make_object_list = True
    allow_empty = True
    allow_future = True


class TaskMonthArchiveView(DateTimeMixin, DynamicDateFieldMixin, MonthArchiveView):
    model = DramatiqTask
    template_name = "archive_month.html"
    allow_future = True
    allow_empty = True


class TaskDayArchiveView(DateTimeMixin, DynamicDateFieldMixin, DayArchiveView):
    model = DramatiqTask
    template_name = "archive_day.html"
    week_format = "%W"
    allow_future = True
    allow_empty = True

dramatiq_dashboard/templates/archive.html
{% extends 'dramatiq_dashboard/base.html' %}
{% load getattr %}

{% block main %}
    <div class="mb-3">
        <a href="{% url 'django_dramatiq_dashboard:task_archive' %}">Archive</a> >
    </div>
    <div class="table-responsive table--no-card m-b-30">
        <table class="table table-borderless table-striped table-earning">
            <thead>
            <tr>
                <th>Task ID</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            {% for task in latest %}
                <tr>
                    <td><a href="{{ task.get_absolute_url }}">{{ task.id }}</a></td>
                    <td>{{ task|getattr:view.get_date_field }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

dramatiq_dashboard/templates/archive_day.html
{% extends 'dramatiq_dashboard/base.html' %}
{% load getattr %}

{% block title %} {{ day }} {% endblock %}

{% block main %}
    <div class="mb-3">
        <a href="{% url 'django_dramatiq_dashboard:task_archive' %}">Archive</a> > <a
            href="{% url 'django_dramatiq_dashboard:task_year_archive' day.year %}"> {{ day.year }}</a> >
        <a href="{% url 'django_dramatiq_dashboard:task_month_archive' day.year day.month %}"> {{ day.month }}</a> >
        <a href="{% url 'django_dramatiq_dashboard:task_day_archive' day.year day.month day.day %}"> {{ day.day }} </a>
    </div>
    <div class="table-responsive table--no-card m-b-30">
        <table class="table table-borderless table-striped table-earning">
            <thead>
            <tr>
                <th>Task ID</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            {% for article in object_list %}
                <tr>
                    <td><a href="{% url 'django_dramatiq_dashboard:executed_detail' article.id %}">{{ article.id }}</a></td>
                    <td>{{ article|getattr:view.get_date_field|date:"F j, Y" }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div style="display: flex; justify-content: space-between;">
        {% if previous_day %}
            <a href="{% url 'django_dramatiq_dashboard:task_day_archive' previous_day.year previous_day.month previous_day.day %}"
               class="btn btn-secondary">
                Previous Day: <span>{{ previous_day }}</span>
            </a>
        {% endif %}
        {% if previous_day and next_day %}--{% endif %}
        {% if next_day %}
            <a href="{% url 'django_dramatiq_dashboard:task_day_archive' next_day.year next_day.month next_day.day %}"
               class="btn" style="background-color: #333; color: white;">
                Next Day: <span>{{ next_day }}</span>
            </a>
        {% endif %}
    </div>
{% endblock %}

dramatiq_dashboard/templates/archive_month.html
{% extends 'dramatiq_dashboard/base.html' %}
{% load getattr %}
{% block main %}
    <div class="mb-3">
        <a href="{% url 'django_dramatiq_dashboard:task_archive' %}">Archive</a> > <a
            href="{% url 'django_dramatiq_dashboard:task_year_archive' month.year %}"> {{ month.year }}</a> >
        <a href="{% url 'django_dramatiq_dashboard:task_month_archive' month.year month.month %}"> {{ month.month }}</a>
        >
        <a href="#"> </a>
    </div>
    <div class="table-responsive table--no-card m-b-30">
        <table class="table table-borderless table-striped table-earning">
            <thead>
            <tr>
                <th>Task ID</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            {% for article in object_list %}
                <tr>
                    <td><a href="{% url 'django_dramatiq_dashboard:executed_detail' article.id %}">{{ article.id }}</a>
                    </td>
                    <td>
                        {{ article|getattr:view.get_date_field|date:"F j, Y" }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div style="display: flex; justify-content: space-between;">
        {% if previous_month %}
            <a href="{% url 'django_dramatiq_dashboard:task_month_archive' previous_month.year previous_month.month %}"
               class="btn btn-secondary">
                Previous Month: <span>{{ previous_month|date:"F Y" }}</span>
            </a>
        {% endif %}
        {% if next_month %}
            <a href="{% url 'django_dramatiq_dashboard:task_month_archive' next_month.year next_month.month %}"
               class="btn" style="background-color: #333; color: white;">
                Next Month: <span>{{ next_month|date:"F Y" }}</span>
            </a>
        {% endif %}
    </div>
{% endblock %}

dramatiq_dashboard/templates/archive_year.html
{% extends 'dramatiq_dashboard/base.html' %}
{% load getattr %}

{% block main %}

    <div class="mb-3">
        <a href="{% url 'django_dramatiq_dashboard:task_archive' %}">Archive</a> > <a
            href="{% url 'django_dramatiq_dashboard:task_year_archive' year.year %}"> {{ year.year }}</a>
    </div>

    <div class="table-responsive table--no-card m-b-30">
        <table class="table table-borderless table-striped table-earning">
            <thead>
            <tr>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            {% for date in date_list %}
                <tr>
                    <td>
                        <a href="{% url 'django_dramatiq_dashboard:task_month_archive' date.year date.month %}">
                            {{ date|date:"F Y" }}</a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>

    <div>
        <div class="mb-3">
            <h4>All tasks for {{ year|date:"Y" }}:</h4>
        </div>
        <div class="table-responsive table--no-card m-b-30">
            <table class="table table-borderless table-striped table-earning">
                <thead>
                <tr>
                    <th>Task ID</th>
                    <th>Date</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td>
                            <a href="{% url 'django_dramatiq_dashboard:executed_detail' obj.id %}">{{ obj.id }}</a>
                        </td>
                        <td>
                            {{ obj|getattr:view.get_date_field|date:"F j, Y" }}
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

    <div class="mt-5" style="display: flex; justify-content: space-between;">
        {% if previous_year %}
            <a href="{% url 'django_dramatiq_dashboard:task_year_archive' previous_year.year %}"
               class="btn btn-secondary">
                Previous Year: <span>{{ previous_year|date:"Y" }}</span>
            </a>
        {% endif %}
        {% if next_year %}
            <a href="{% url 'django_dramatiq_dashboard:task_year_archive' next_year.year %}" class="btn"
               style="background-color: #333; color: white;">
                Next Year: <span>{{ next_year|date:"Y" }}</span>
            </a>
        {% endif %}
    </div>
{% endblock %}

dramatiq_dashboard/templates/dramatiq_dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title Page-->
    {% block title %}
        <title>Django dramatiq dashboard</title>
    {% endblock %}

    <!-- Fontfaces CSS-->
    <link href="{% static 'dramatiq_dashboard/css/font-face.css' %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'dramatiq_dashboard/vendor/bootstrap-4.1/bootstrap.min.css' %} " rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'dramatiq_dashboard/css/theme.css' %} " rel="stylesheet" media="all">

</head>

<body class="animsition">
<div class="">
    <!-- PAGE CONTAINER-->
    <div class="">
        <!-- HEADER DESKTOP-->
        <header class="header-desktop">
            <div class="section__content section__content--p30">
                <div class="container-fluid" style="display: flex; align-items: center">
                    <div class="header-wrap">
                        <h1>Django dramatiq dashboard</h1>
                    </div>
                    <div class="ml-5">
                        <a href="{% url 'django_dramatiq_dashboard:executed_list' %}" class="btn btn-light">All
                            tasks</a>
                        <a href="{% url 'django_dramatiq_dashboard:task_year_archive' date.year %}"
                           class="ml-3 btn btn-light">Year</a>
                        <a href="{% url 'django_dramatiq_dashboard:task_month_archive' date.year date.month %}"
                           class="ml-3 btn btn-light">Month</a>
                        <a href="{% url 'django_dramatiq_dashboard:task_day_archive' date.year date.month date.day %}"
                           class="ml-3 btn btn-light">Day</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- END HEADER DESKTOP-->

        <!-- MAIN CONTENT-->
        <div class="main-content">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    <div class="">
                        <div class="">
                            {% block main %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Jquery JS-->
<script src="{% static 'dramatiq_dashboard/vendor/jquery-3.2.1.min.js' %}"></script>
<!-- Bootstrap JS-->
<script src="{% static 'dramatiq_dashboard/vendor/bootstrap-4.1/popper.min.js' %} "></script>
<script src="{% static 'dramatiq_dashboard/vendor/bootstrap-4.1/bootstrap.min.js' %}"></script>
</body>

</html>
<!-- end document-->

dramatiq_dashboard/templates/dramatiq_dashboard/detail.html
{% extends 'dramatiq_dashboard/base.html' %}
{% load timetags %}

{% block main %}
    <div class="mb-3">
        <a href="{% url 'django_dramatiq_dashboard:executed_list' %}">All tasks</a> > <a
            href="{% url 'django_dramatiq_dashboard:executed_detail' object.id %}">{{ object.id }}</a>
    </div>
    <div class="table-responsive table--no-card m-b-30">
        <table class="table table-borderless table-striped table-earning">
            <thead style="display:inline-block;">
            <tr>
                <th>ID</th>
            </tr>
            <tr>
                <th>Actor Name</th>
            </tr>
            <tr>
                <th>Queue Name</th>
            </tr>
            <tr>
                <th>Status</th>
            </tr>
            <tr>
                <th>Created At</th>
            </tr>
            <tr>
                <th>Updated At</th>
            </tr>
            <tr>
                <th>Result</th>
            </tr>

            </thead>
            <tbody style="display:inline-block;">
            <tr>
                <td>{{ object.id }}</td>
            </tr>
            <tr>
                <td>{{ object.actor_name }}</td>
            </tr>
            <tr>
                <td>{{ object.queue_name }}</td>
            </tr>
            <tr>
                <td>{{ object.status }}</td>
            </tr>
            <tr>
                <td>{{ object.created_at }}</td>
            </tr>
            <tr>
                <td>{{ object.updated_at }}</td>
            </tr>
            <tr>
                <td>{{ object.result }}</td>
            </tr>

            </tbody>
        </table>
    </div>
    <h2 class="mb-3">Message data:</h2>
    <div class="table-responsive table--no-card m-b-30">
        <table class="table table-borderless table-striped table-earning">
            <thead style="display:inline-block;">
                <tr>
                    <th>queue_name</th>
                </tr>
                <tr>
                    <th>actor_name</th>
                </tr>
                <tr>
                    <th>args</th>
                </tr>
                <tr>
                    <th>kwargs</th>
                </tr>
                <tr>
                    <th>options</th>
                </tr>
                <tr>
                    <th>message_id</th>
                </tr>
                <tr>
                    <th>message_timestamp</th>
                </tr>
            </thead>
            <tbody style="display:inline-block;">
                    {% for value in object.message %}
                        <tr>
                            <td>{{ value }}</td>
                        </tr>
                    {% endfor %}
            </tbody>
        </table>
    </div>

    <style>
        td {
            line-height: 1;
            padding: 22px 40px !important;
            width: 1240px !important;
        }
    </style>
{% endblock %}

dramatiq_dashboard/templates/dramatiq_dashboard/list.html
{% extends 'dramatiq_dashboard/base.html' %}

{% block main %}
    <div class="mb-3">
        <a href="{% url 'django_dramatiq_dashboard:executed_list' %}">All tasks</a> >
    </div>
    <div class="table-responsive table--no-card m-b-30">
        <table class="table table-borderless table-striped table-earning">
            <thead>
            <tr>
                <th>ID</th>
                <th>Status</th>
                <th>Created at</th>
                <th>Updated at</th>
            </tr>
            </thead>
            <tbody>
            {% for task in object_list %}
                <tr>
                    <td><a href="{% url 'django_dramatiq_dashboard:executed_detail' task.id %}">{{ task.id }}</a></td>
                    <td>{{ task.status }}</td>
                    <td>{{ task.created_at }}</td>
                    <td>{{ task.updated_at }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}